disabled_rules:
    - force_cast
    - identifier_name
    - line_length
    - notification_center_detachment

opt_in_rules:
    - private_action
    - unused_import

trailing_comma:
    mandatory_comma: true
